spring:
  application:
    name: CentroSer
  datasource:
    url: jdbc:postgresql://localhost:5432/centroser
    password: 1234*
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    private: classpath:app.key
    public: classpath:app.pub